services:
  mt5:
    ports:
      - "8080:8080"
    volumes:
      - ./docker/mt5/:/root/.wine/drive_c/fx
    environment:
      - ACCOUNT=nghia
      - PASSWORD=123456
      - SERVER=nghia
    deploy:
      replicas: 1