services:
  mt5:
    image: asc686f61/fx-mt5:test
    build:
      context: .
      dockerfile: mt5/Dockerfile
    ports:
      - "8085:8080"
      - "5929:8080"
      - "8000:8000"
    # volumes:
    #   - ./docker/mt5/:/root/.wine/drive_c/fx
    environment:
      - ACCOUNT=nghia
      - PASSWORD=123456
      - SERVER=nghia
    deploy:
      replicas: 1
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.mt5.entrypoints=http'
      - 'traefik.http.routers.mt5.rule=Host(`webdn.online`)'
      - 'traefik.http.routers.mt5-secure.entrypoints=https'
      - 'traefik.http.routers.mt5-secure.rule=Host(`webdn.online`)'
      - 'traefik.http.routers.mt5-secure.tls.certresolver=letsencrypt'

    networks:
      - traefik  # Kết nối container Next.js với network traefik
networks:
  traefik:
    external: true  # Đảm bảo Traefik và các dịch vụ container sử dụng cùng mạng này
